# Generated by Django 4.1.6 on 2023-04-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='link_2',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='link_1',
            new_name='post',
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category')),
            ],
        ),
    ]
