# Generated by Django 4.1.6 on 2023-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_news',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_news',
            field=models.CharField(max_length=255),
        ),
    ]
