# Generated by Django 4.1.6 on 2023-03-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='link_2',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='link_1',
            new_name='post',
        ),
    ]
