# Generated by Django 4.1.6 on 2023-03-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_link_2_postcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='category',
        ),
    ]
