# Generated by Django 4.1.6 on 2023-03-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
