# Generated by Django 4.1.6 on 2023-03-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_categorylistview_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
