# Generated by Django 4.1.6 on 2023-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_category_name_remove_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=65, unique=True),
            preserve_default=False,
        ),


    ]
