# Generated by Django 4.1.6 on 2023-03-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_name_delete_categorylistview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryListView',
        ),
    ]
